### ISSUE TITLE
camera positioning question

### ISSUE THREAD

**Issue by YoniChechik** [mmatl/pyrender#111]
This short snippet is from the quick-start tutorial. can you explain this matrix? what is the connection between this matrix and R|t matrix of opencv (and the rest of the world).
I'm trying to build a AR app while using pyrender + opencv solvePnP R,t matrix and ploting the resulting color image on a given image.

```
>>> s = np.sqrt(2)/2
>>> camera_pose = np.array([
...    [0.0, -s,   s,   0.3],
...    [1.0,  0.0, 0.0, 0.0],
...    [0.0,  s,   s,   0.35],
...    [0.0,  0.0, 0.0, 1.0],
... ])
```

**Comment by YoniChechik** [comment]
got it...
for anyone interested: https://stackoverflow.com/a/18643735/4879610

**Comment by Frank-Dz** [comment]
> got it...
> for anyone interested: https://stackoverflow.com/a/18643735/4879610

Hi, could you provide a small demo code for this function?

**Comment by liwang0621** [comment]
> 明白了...... 对于任何感兴趣的人：[https ://stackoverflow.com/a/18643735/4879610](https://stackoverflow.com/a/18643735/4879610)

I have the same problem, but I still haven't solved it. Can you give me some examples
