### ISSUE TITLE
Need help understanding depth maps generated

### ISSUE THREAD

**Issue by jiunyen-ching** [mmatl/pyrender#119]
Hi @mmatl, according to the documentation, the data type of depth_im is float32. 

How should I convert the pixel values to a real-world dimension i.e. in meters?

Edit: Taking a depth map from NYUv2 dataset for example, the depth map is in 16-bit format, 1 mm resolution. The pixel values range from 0 - 65535 and the scaling factor is 1000. So, a pixel with value of 1000 is equivalent to 1 meter in real-world dimension. 

Could you help me to interpret the depth map generated using pyrender?

**Comment by jiunyen-ching** [comment]
Update: According to this comment on IntelRealSense, 

> FYI: In ROS the depth is expected to be in one of 2 formats: 32-bit float in meters or 16-bit unsigned integers in millimeter resolution. This ros realsense driver currently publishes depth in 16-bit 1 millimeter resolution.

Does this apply the same for pyrender? If so, correct me if I'm wrong, I should interpret the pixel values as the real-world distance in meters?

Link: https://github.com/IntelRealSense/realsense-ros/issues/41#issuecomment-220641708

**Comment by mmatl** [comment]
They're real-world coordinates in meters.

**Comment by jiunyen-ching** [comment]
I see.. Does this also apply to objects' dimensions? i.e. if I have a cube with dimensions 1 x 1 x 1 unit^3, is this also equivalent to 1 meter x 1 meter x 1 meter cube?

**Comment by mmatl** [comment]
Yes, that's correct.

**Comment by jiunyen-ching** [comment]
I see.. Thanks for the clarification!
