### ISSUE TITLE
Annotation Mask

### ISSUE THREAD

**Issue by lix4** [mmatl/pyrender#143]
Is there a way to annotate or somehow mark on 3D scene mesh and generate 2D mask with rendered image? I am not saying instance level but annotation level. For example, I only want to generate 2D mask on the handle part of a coffee mug. Therefore, I only want to mark the handle part on 3D mesh.

**Comment by michele-arrival** [comment]
if your model is made of separate bodies (say one for the mug body, and one for the handle) you can add each body to the scene as a separate node. Then you can render using the segmentation flag, and pass as a dictionary one that has a different color for each node/tag in the dictionary.

does it make sense?

**Comment by lix4** [comment]
> if your model is made of separate bodies (say one for the mug body, and one for the handle) you can add each body to the scene as a separate node. Then you can render using the segmentation flag, and pass as a dictionary one that has a different color for each node/tag in the dictionary.
> 
> does it make sense?
Yes, make sense to me. Thanks!
