### ISSUE TITLE
ValueError: Invalid device ID(0)

### ISSUE THREAD

**Issue by SLTK1** [mmatl/pyrender#151]
Firstly I tried my programme directly on a physical computer with NVIDIA GPU, it works.

Then I tried to use pyrender in docker with egl but I got this error, File 'xxx/pyrender/platforms/egl/py', line 83, in get_device_by_index raise ValueError('Invalid device ID ({})'.format(device_id, len(devices)))  ValueError: Invalid device ID(0)

It seems that NVIDIA GPU cannot be found by opengl. but nvidia-smi can show the GPU information.

**Comment by ShuangjunLiu** [comment]
Same here.

**Comment by SLTK1** [comment]
My docker is OK but GPU dont support OPENGL

**Comment by lllllialois** [comment]
did u fix it？

> My docker is OK but GPU doesn't support OpenGL

**Comment by trancelestial** [comment]
@SLTK1 Any updates?

**Comment by lunalulu** [comment]
Any updates?

**Comment by Leestronger** [comment]
> Any updates?

try this?
https://github.com/mmatl/pyrender/issues/247#issuecomment-1486423328
