### ISSUE TITLE
Mesh.from_trimesh CPU utilization - maxes out all 32 cores

### ISSUE THREAD

**Issue by henryclever** [mmatl/pyrender#16]
Hi,

I've found that the command `Mesh.from_trimesh()` seems to use all of my CPU cores, i.e. it uses some sort of multithreading trick to run faster. Problem is, I have a giant computer with 32 cores. So when I run this command repeatedly it uses all the cores to near 100% but doesn't run much faster, presumably because all the processing is being used to transfer information between cores rather than do something useful. I'd like to reduce this to 4 or 8 cores. Is there an easy way to do that?

Thanks!
Henry C.

Thanks!
Henry C.

**Comment by mmatl** [comment]
Hi Henry,

I'm not seeing that behavior anywhere on my machine. I didn't implement any multithreading in my load code, so if it's happening, it's happening in `trimesh`. Can you give me an example of the mesh file you're trying to load?

**Comment by henryclever** [comment]
Hi Matt,

Here's my code. When I comment out the second line (the pyrender command) but keep the trimesh command, it appears to only use up a single core of my CPU as expected. 
```
tm = trimesh.base.Trimesh(vertices=smpl_vertices, faces=smpl_faces)
smpl_mesh = pyrender.Mesh.from_trimesh(tm, material=self.human_mat, wireframe = True)
```

zip file with numpy arrays for faces and vertices below:
[verts_faces.zip](https://github.com/mmatl/pyrender/files/3104921/verts_faces.zip)

There are about 7000 vertices and a similar number of faces.

Henry

**Comment by mikedh** [comment]
Hey Henry, that mesh looks pretty reasonable on my computer, I didn't notice any core-maxing with the latest versions of trimesh/pyrender. What does it look like if you try running it with a profiler, like [cProfile](https://docs.python.org/ko/3.6/library/debug.html) or [pyinstrument](https://github.com/joerick/pyinstrument)?
 
```
In [1]: import numpy as np

In [2]: import trimesh

In [3]: v = np.load('smpl_vertices.npy')

In [4]: f = np.load('smpl_faces.npy')

In [5]: %timeit m = trimesh.Trimesh(v, f)
The slowest run took 10.21 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 3: 2.67 ms per loop

In [6]: m = trimesh.Trimesh(v, f)

In [8]: import pyrender

In [9]: %timeit p = pyrender.Mesh.from_trimesh(m)
The slowest run took 25.02 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 243 µs per loop

```

**Comment by henryclever** [comment]
Hi,
So I think I have found how I can reproduce the problem better, but I have not solved it and it does not appear to happen when using pyrender and trimesh in isolation from the rest of my program.

If I don't regenerate the mesh and just use it as you did, there is no problem. However, each time I loop I'm regenerating the mesh vertices and faces using the [SMPL human parametrization](http://files.is.tue.mpg.de/black/papers/SMPL2015.pdf). If I print out the mesh verts and faces to the terminal, use the trimesh command, etc, there is no extra CPU usage. But If I regenerate the mesh vertices and use `Mesh.from_trimesh()` concurrently, the problem exists. 

Here are screenshots showing a hacky profiling:
Normal case:
![only_trimesh_command](https://user-images.githubusercontent.com/7378478/56534857-81114280-6528-11e9-9cc5-a892a5ac7663.png)

Smpl regen + trimesh + pyrender: (problem case, it looks ludicrous on the 32 core machine)
![both_trimesh_and_pyrender](https://user-images.githubusercontent.com/7378478/56534915-98e8c680-6528-11e9-9020-32a023afe769.png)

So weird.

Henry C.

**Comment by henryclever** [comment]
Anyway, thanks to Matt and Mike for the quick responses!
Henry C.

**Comment by mikedh** [comment]
Oh interesting. One thing it could be is auto generated vertex normals requested in the from trimesh call. Those are calculated with a scipy sparse matrix which is super fast and heavily parallelized. Maybe try from_trimesh(smooth=False) and see if it still happens?

**Comment by henryclever** [comment]
Mike,
Interesting thought. 

I tried setting smooth to False- doesn't work, though. Same problem.

Henry C.

**Comment by henryclever** [comment]
Also,

I tried changing the vertex positions manually every loop rather than having the SMPL parameterization do it - by adding a very small increment to the float value of each vertex x,y,z of 0.00001. In that case, the problem goes away. So it appears it's not just a matter of recreating arbitrary vertices and faces, rather it's something to do with the SMPL calculation.

Henry C.

**Comment by mmatl** [comment]
Closing this as it seems to not be an issue that can be fixed in pyrender.

**Comment by LogWell** [comment]
I have to render a series of meshes[`path_objs`]. When I do as the following, memory grows until it crashes. How to avoid this situation?

Memory growth seems to be related to `mesh_pr = pyrender.Mesh.from_trimesh(mesh_tri)`.

THANKS~
```
scene = pyrender.Scene(bg_color=[1.0, 1.0, 1.0, 1.0], ambient_light=(0.5, 0.5, 0.5))

cam = pyrender.PerspectiveCamera(yfov=np.pi / 4., znear=0.05, zfar=5.0, aspectRatio=1.0)
scene.add(cam, pose=np.eye(4))

r = pyrender.OffscreenRenderer(viewport_width=1080,
                               viewport_height=1080,
                               point_size=1.0)

for path_obj in path_objs:
    mesh_tri = trimesh.load(path_obj, process=False)
    mesh_pr = pyrender.Mesh.from_trimesh(mesh_tri)
    node_mesh = pyrender.Node(mesh=mesh_pr)
    scene.add_node(node_mesh)

    color, depth = r.render(scene)
    imageio.imwrite(path_img, color)
    imageio.imwrite(path_img[:-4] + '_d.png', (depth * 1000).astype(np.uint16))

    scene.remove_node(node_mesh)
```

**Comment by monacv** [comment]
@mikedh could you please let me know where you downloaded the `smpl_vertices.npy` from?

I cannot find it on SMPL website Download page
![Screenshot from 2021-03-23 21-45-23](https://user-images.githubusercontent.com/76495162/112241916-425afa00-8c21-11eb-9b55-189f2ef805ac.png)
