### ISSUE TITLE
scene.add(node, pose) and scene.set_pose(node, pose) result in different pose matrix

### ISSUE THREAD

**Issue by pomelyu** [mmatl/pyrender#168]
First of all, thanks for this nice repo.

I found `scene.get_pose(node)` return the different pose assigned by `scene.add(node, pose)` but the same as `scene.set_pose(node, pose)`

```python
import pyrender
import numpy as np

scene = pyrender.Scene(ambient_light=(10, 10, 10), bg_color=(0, 0, 0))
pose = np.array([
    [ 7.52572324e-01, -9.65759494e-02,  4.45809367e-01,  8.83958734e+04],
    [ 4.80993599e-02,  7.51036085e-01,  2.85672060e-01,  5.29484120e+04],
    [-2.20698617e-01, -1.17395630e-01,  1.57460561e+00,  3.89152123e+05],
    [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00],
])

node_camera = scene.add(camera, pose=pose)
print(scene.get_pose(node_camera))
# [[ 7.51660479e-01 -8.90269514e-02  4.43786497e-01  8.83958734e+04]
#  [ 5.48318208e-02  7.52259994e-01  2.94153501e-01  5.29484120e+04]
#  [-2.22230795e-01 -1.15511695e-01  1.57361514e+00  3.89152123e+05]
#  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

scene.set_pose(node_camera, pose)
print(scene.get_pose(node_camera))
# [[ 7.52572324e-01 -9.65759494e-02  4.45809367e-01  8.83958734e+04]
#  [ 4.80993599e-02  7.51036085e-01  2.85672060e-01  5.29484120e+04]
#  [-2.20698617e-01 -1.17395630e-01  1.57460561e+00  3.89152123e+05]
#  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
```
It seems the rotation part is modified by `scene.add`. Not all the pose matrix cause this problem, but in some case the difference will be huge. Thanks

**Comment by mmatl** [comment]
Looks like your matrix didn't have a determinant of 1.0, so when the matrix was decomposed into T, R, and S values, the resulting matrix was non-identical. I've pushed a change that should preserve the default matrix you provide, though. Will be in a future version update.

**Comment by pomelyu** [comment]
Thanks for the quick reply. I see in the last version, [the order in matrix setter](https://github.com/mmatl/pyrender/blob/dd6dbd895aada77f33975cedaad039ac58811ea4/pyrender/node.py#L215) is changed to prevent recalculating the rotation matrix. I also found out the matrix I provide is not the true rotation matrix. I think it is the main problem.

By the way, I also notice `scene.set_pose(node, pose)` [directly set the private member](https://github.com/mmatl/pyrender/blob/dd6dbd895aada77f33975cedaad039ac58811ea4/pyrender/scene.py#L478) and skip the setter function. Is it expected? It might skip the calculation about rotation, scale and translation.
