### ISSUE TITLE
how to project a image with spotlight in pyrender?

### ISSUE THREAD

**Issue by kaixin-bai** [mmatl/pyrender#171]
I try to use the code below to project an image with spotlight in pyrender, but I fail.
```python
spot_l = SpotLight(color=np.ones(3), intensity=10.0,
                   innerConeAngle=np.pi/16, outerConeAngle=np.pi/6)
from PIL import Image
texture_im = np.array(Image.open(image_path))
spot_l.shadow_texture = Texture(source=texture_im,
                                source_channels="RGB",
                                width=2525,
                                height=1419, data_format=OpenGL.GL.GL_FLOAT)
```

**Comment by mmatl** [comment]
The shadow texture is not meant to be used in this way. Shadow textures are written to as part of the shadowmapping pass and should not be used directly. See here for details: https://learnopengl.com/Advanced-Lighting/Shadows/Shadow-Mapping
