### ISSUE TITLE
Depth image value range from orthographic camera

### ISSUE THREAD

**Issue by ChenXuelinCXL** [mmatl/pyrender#19]
Hi, @mmatl , I am not sure if I am using the orthographic camera in the right way. But I found that the value range of the depth map from orth. camera looks weird, it is not of physical unit.

When I set a perspective camera to scan a chair at distance around 1 meter, I can get a depth map which has value range between 0 and ~0.75. This is good, in meter.

However, when I set an orthographic camera to scan, like the code below:
camera = pyrender.OrthographicCamera(xmag=.5, ymag=.5, znear=0.05, zfar=100)
then, the value range of the depth map is like 0 - 0.05138555, which is obviously not physically meaningful, I have been looking into this for a while but still have no idea.

Can you please help me out. :)
Thanks!

**Comment by ChenXuelinCXL** [comment]
Hi, @mmatl , I figured it out, for orthographic camera, a different unprojection matrix should be used when unproject depth from the buffer to real value.

Please let me know if and how I can help.:)

**Comment by ChenXuelinCXL** [comment]
Hi, @mmatl , I think I figured it out and fixed it in my local, let me know if and how I can help to fix the bug. :)

**Comment by mmatl** [comment]
@ChenXuelinCXL sounds awesome, thanks for fixing the issue! When you have time, feel free to make a PR on this and I'll merge it right in! :)

**Comment by ChenXuelinCXL** [comment]
@mmatl , glad if I can help, just started a PR and closing this. :)
