### ISSUE TITLE
Problem in rendering with ply file

### ISSUE THREAD

**Issue by staceycy** [mmatl/pyrender#21]
Hi, 
Thanks for contributing this library. 

I tried to render with objects in ply file format with following codes: 

> obj1_trimesh = trimesh.load('./models/obj_01.ply')
> obj1_mesh = Mesh.from_trimesh(obj1_trimesh)
> scene.add(obj1_mesh)

However, nothing appeared in the rendered images. 
The zip format of ply file is attached. 
[obj_01.ply.zip](https://github.com/mmatl/pyrender/files/3147123/obj_01.ply.zip)

Could you please give some advice? 
Thanks in advance!

Best, 
Stacey

**Comment by mmatl** [comment]
You probably just have your camera pointing the wrong direction. I had no trouble rendering your mesh in pyrender:

![image](https://user-images.githubusercontent.com/6517318/57262506-33650180-7021-11e9-855e-1a1eaaadb1c8.png)

**Comment by staceycy** [comment]
Hi,

Thank you very much for your quick response. 
I set the camere same as the one in the tutorial. Could you please share your codes for rendering?  
Thanks.

**Comment by mmatl** [comment]
I just tossed this into the viewer with the default camera. You need to make sure that you choose a camera pose that is looking at your object. Pyrender uses OpenGL camera coordinates, which means that the Z-axis of the camera faces away from the scene.

**Comment by staceycy** [comment]
Thank you for your help. 
I can render the object now :relaxed:
