### ISSUE TITLE
pyrender/platforms/osmesa.py", line 19, in init_context     from OpenGL.osmesa import ( ImportError: cannot import name 'OSMesaCreateContextAttribs' from 'OpenGL.osmesa'

### ISSUE THREAD

**Issue by jinfagang** [mmatl/pyrender#210]
pyrender/platforms/osmesa.py", line 19, in init_context
    from OpenGL.osmesa import (
ImportError: cannot import name 'OSMesaCreateContextAttribs' from 'OpenGL.osmesa'

Please upgrade PyOpenGL requirements to 

![image](https://user-images.githubusercontent.com/21303438/149520857-72b1e450-dc2a-4d04-8ae1-61b601ecbc22.png)

**Comment by ktiwary2** [comment]
I'm facing the same issue, were you able to fix it?

**Comment by jinfagang** [comment]
@ktiwary2 No, I uninstalled pyrender, and block this stupid lib forever, it introduced a lot of problem on any platform. I turned using real render, `pip install realrender`. It was faster than pyrender, gives me realtime render on CPU. while pyrender need about 70ms -80ms, but realrender just need 4ms....
