### ISSUE TITLE
Unable render 2d image from ply file with a given camera pose

### ISSUE THREAD

**Issue by ankurgupta26** [mmatl/pyrender#24]
Hi @mmatl , I am trying to render 2d image with a given perspective using a given camera pose. The camera pose that I am using is :

camera pose :  [[ 0.69210445  0.03735558  0.72083007 -0.48671459]
 [ 0.009216    0.99812114 -0.06057437 -0.02976532]
 [-0.72173852  0.04856696  0.69045982  0.42914029]
 [ 0.          0.          0.          1.        ]]

I have also attached the .ply file for your reference.
[surface-L2-clean.ply.zip](https://github.com/mmatl/pyrender/files/3152510/surface-L2-clean.ply.zip)

Thanks.

**Comment by mmatl** [comment]
Your camera is backwards, I think. Pyrender uses OpenGL coordinates, which means that the z-axis should face away from the scene. I'll add this to the docs to reduce confusion.

**Comment by mmatl** [comment]
It's now in the docs here: https://pyrender.readthedocs.io/en/latest/examples/cameras.html. Closing this issue for now, let me know if you have further questions.
