### ISSUE TITLE
convert image coordinates to world coordinates

### ISSUE THREAD

**Issue by ma-rv** [mmatl/pyrender#28]
Hey, I have the following setup..

- Object Pose is fixed (identitiy matrix)
- Camera is at camera_pose (identity matrix + translated on z axis)

..and im trying to convert image coordinates back to world coordinates the following way:

T_ext = camera_pose
T_int = camera.get_projection_matrix(w,h)
X_world = T_ext⁻¹ * T_int⁻¹ * X_img

Since it doesn't give any reasonable results there has to be some error in my approach. Would be very thankful if someone could help me out!

**Comment by silence401** [comment]
could yout tell me how did you solve this problem

**Comment by D0miH** [comment]
I have the same problem that the result is not reasonable. Did you solve this problem @silence401, @ma-rv ? How did you project the point to screen/image coordinates?

**Comment by silence401** [comment]
> I have the same problem that the result is not reasonable. Did you solve this problem @silence401, @ma-rv ? How did you project the pixel to world coordinates?

I write a function to convert it.
https://github.com/silence401/pyrender/blob/e30f7866bc233f4b573ac39d9f371d59a720276d/examples/get_pose.py#L26

**Comment by D0miH** [comment]
Oh wow, that is very nice. Thanks a lot!
