### ISSUE TITLE
The window pops up but only displays a black screen, with no rendered content. 

### ISSUE THREAD

**Issue by Logic-TARS** [mmatl/pyrender#299]
Ubuntu 22.04  Python 3.9 RTX 4090 
Use SSH（remote desktop ）
![屏幕截图 2024-12-21 134308](https://github.com/user-attachments/assets/26ffbe1a-33b0-45f0-8bc9-aeff42ade601)
First，there is a problem that **"pyglet.gl.ContextException: Could not create GL context "**
and I use this mothed.
`conda install -c conda-forge libstdcxx-ng `
This resolved the initial error, but a new issue has arisen. When running the program, the window successfully pops up, but the content only displays a black screen
![屏幕截图 2024-12-21 134225](https://github.com/user-attachments/assets/e99486a1-a1cb-4efc-927e-535be2034e88)
Meanwhile, I change this:
![屏幕截图 2024-12-21 135702](https://github.com/user-attachments/assets/222303d0-396b-45fc-8dc6-46b5fc7988c1)
but it does't work.

I don't know how to sovle it :(

**Comment by Irving87** [comment]
Hi, how did you sovle this problem？
