### ISSUE TITLE
bg_color (4)

### ISSUE THREAD

**Issue by oarriaga** [mmatl/pyrender#31]
Hi,
in `Scene`, `bg_color` has the following docstring:

> bg_color ((4,) float, optional) – Background color of scene.

However [later in the documentation ](https://pyrender.readthedocs.io/en/latest/generated/pyrender.Scene.html#pyrender.Scene.bg_color) is estipulated that it should be:

> Type: | (3,) float

Should it be 3 or 4?

P.S.
Great project :)!

**Comment by mmatl** [comment]
Either works, actually :)

**Comment by oarriaga** [comment]
But 4 would be for which color model?

**Comment by mikedh** [comment]
`(4,)` colors are interpreted as RGBA, where the last value is alpha (i.e. transparency). If you pass `(3,)` colors it's assuming it's a fully opaque RGB color.

**Comment by oarriaga** [comment]
Oh OK, thank you :)
