### ISSUE TITLE
Trying OffscreenRenderer failed with osmesa.

### ISSUE THREAD

**Issue by datased2019** [mmatl/pyrender#37]
I just follow the document and install mesa deb in my headless ubuntu. After that, i install the fock PyOpengl and got the ERROR:
ERROR: pyrender 0.1.25 has requirement PyOpenGL==3.1.0, but you'll have pyopengl 3.1.3b2 which is incompatible.
(Maybe it is OK because your fock version is newer than 3.1)

But when i try using osmesa for offscreen render. I got the Error like this:
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import pyrender
  File "/usr/local/lib/python3.5/dist-packages/pyrender/__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "/usr/local/lib/python3.5/dist-packages/pyrender/light.py", line 11, in <module>
    from .texture import Texture
  File "/usr/local/lib/python3.5/dist-packages/pyrender/texture.py", line 8, in <module>
    from OpenGL.GL import *
  File "/usr/local/lib/python3.5/dist-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/local/lib/python3.5/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/usr/local/lib/python3.5/dist-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/usr/local/lib/python3.5/dist-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'

I have no idea how to solve this.

**Comment by YoelShoshan** [comment]
I got the exact same error. I solved it by adding:
export PATH=my/path/to/llvm-install/bin:$PATH
export LD_LIBRARY_PATH=my/path/to/llvm-install/lib:$LD_LIBRARY_PATH

(replace my/path/to/llvm-install/ with whatever toolchain that is relevant to you)

I checked and only the LD_LIBRARY_PATH was needed.

A bit more explanation - since I don't have admin rights on the server that I'm running, I've built llvm from source in order to build osmesa from source.

I suppose that PyOpenGL needed the libraries in order to open the shared objects.

Was a bit of a nightmare to solve, but I finally have a function offscreen rendering :)

**Comment by datased2019** [comment]
> I got the exact same error. I solved it by adding:
> export PATH=my/path/to/llvm-install/bin:$PATH
> export LD_LIBRARY_PATH=my/path/to/llvm-install/lib:$LD_LIBRARY_PATH
> 
> (replace my/path/to/llvm-install/ with whatever toolchain that is relevant to you)
> 
> I checked and only the LD_LIBRARY_PATH was needed.
> 
> A bit more explanation - since I don't have admin rights on the server that I'm running, I've built llvm from source in order to build osmesa from source.
> 
> I suppose that PyOpenGL needed the libraries in order to open the shared objects.
> 
> Was a bit of a nightmare to solve, but I finally have a function offscreen rendering :)

Thx YoelShoshan for your kindly reply. I just install osmesa from deb and set the PATH and LD_LIBRARY_PATH just as you did but same error. I don't know if I need to follow your guide to build llvm and osmesa by myself and try again.
I will give it a try. 
Really appreciate your help.

**Comment by datased2019** [comment]
I tried to build everything from sources and it finnally works.
Closed. 

Thx a lot, YoelShoshan.
