### ISSUE TITLE
Render color images with alpha channel

### ISSUE THREAD

**Issue by ChenXuelinCXL** [mmatl/pyrender#4]
Hi @mmatl , I am using the pyrender to render some point clouds in off-screen mode.

I am wondering if it is possible to render images with alpha channel?

Thanks!

**Comment by ChenXuelinCXL** [comment]
Hi @mmatl , hah, I am also wondering why you did not add point_size parameter for the offscreen renderer, or you just forgot it, lol. Maybe it'd better if we can control the point size even in the offscreen mode.

**Comment by mmatl** [comment]
Hi @ChenXuelinCXL! Just fixed these features in c322a0015ced82f7e253bf791eba5db096f3da55.

Just set the scene's background color to have transparency (i.e. alpha = 0). Now, the offscreen render will return the full RGBA color matrix. Save it out with PIL to view it (make sure to save as a PNG).

For example:
![image](https://user-images.githubusercontent.com/6517318/52977476-3e918500-3382-11e9-98b2-1ddc62580a7f.png)

**Comment by mmatl** [comment]
Sorry, had to fix a few tests. Deploying this now to PyPi as version 0.1.10.

**Comment by ChenXuelinCXL** [comment]
Hi @mmatl , wow, thank you so much! BTW, I am rendering point clouds, currently, I am trying to convert each point into a sphere mesh, so I can control the rendered point size via changing the radius of the spheres, this is obviously inefficient. So could you please tell me if there is a way to directly rendering the point clouds with the control of the point size?

Thank you!

**Comment by mmatl** [comment]
Yeah, absolutely! There's a simple option for this if you're okay with your points being screen-space quads.

```python
import pyrender
import numpy as np
import trimesh

m = trimesh.creation.icosahedron()
pts = m.vertices
colors = np.random.uniform(size=pts.shape)

s = pyrender.Scene()
mn = pyrender.Mesh.from_points(pts, colors=colors)
s.add(mn)
pyrender.Viewer(s, use_raymond_lighting=True, point_size=10)
```

![points](https://user-images.githubusercontent.com/6517318/52981355-275b9300-3394-11e9-8cc7-a46cd52e7d8d.png)

**Comment by ChenXuelinCXL** [comment]
Thanks for your reply! Actually I am using offscreen renderer to render the point cloud. However, there is no option for setting this kind of point size parameter, I have looked at the documents, I think there is no such thing for offscreen rendering, or am I missing something?

**Comment by mmatl** [comment]
@ChenXuelinCXL Yeah, it's actually there! Just forgot to add it to the docstring -- it should be visible now: https://pyrender.readthedocs.io/en/latest/generated/pyrender.offscreen.OffscreenRenderer.html#pyrender.offscreen.OffscreenRenderer.

**Comment by mmatl** [comment]
I'm going to write this up in the docs. FYI, with the newest commit, it would look something like this for getting RGBA:

```python
color, depth = renderer.render(scene, flags=RenderFlags.NONE) # Returns 3-channel color
color, depth = renderer.render(scene, flags=RenderFlags.RGBA) # Returns 4-channel color
```

**Comment by ChenXuelinCXL** [comment]
Hi @mmatl , big thanks for all of this! I am trying this!

**Comment by mmatl** [comment]
@ChenXuelinCXL no worries at all, happy you're using the code! Let me know if you have any issues.

**Comment by mmatl** [comment]
@ChenXuelinCXL Were you able to get it working?

**Comment by ChenXuelinCXL** [comment]
@mmatl , Yes!, After I got the latest pyrender via pip install, now I can render images with alpha channel, and render point clouds with point size control, in offscreen mode. Thank you so much for this easy-to-use code and your kindly help!

**Comment by mmatl** [comment]
No worries! Going to close the issue for now, feel free to open another if you run into any issues.
