### ISSUE TITLE
Capture Screenshot of Loaded Model?

### ISSUE THREAD

**Issue by infosisio** [mmatl/pyrender#47]
Thanks for the great tool.

I am looking to capture a screenshot of my loaded model, ideally headless. 

The goal is to use this to generate model thumbnails.

This is my simple code for loading:

```
import trimesh
import pyrender
fuze_trimesh = trimesh.load('cup.stl')
mesh = pyrender.Mesh.from_trimesh(fuze_trimesh)
scene = pyrender.Scene()
scene.add(mesh)
pyrender.Viewer(scene, use_raymond_lighting=True)
```

I am on Windows 10.
Many thanks.

**Comment by mmatl** [comment]
I'd recommend using the offscreen renderer to do headless rendering of an RGB image.
