### ISSUE TITLE
Any examples on event handling for Viewer class?

### ISSUE THREAD

**Issue by mrlooi** [mmatl/pyrender#5]
It's not clear how to register and trigger events in the Viewer class
e.g. on_mouse_release, on_mouse_press, etc

**Comment by mrlooi** [comment]
Or is the only way to override the Viewer class methods?

**Comment by mmatl** [comment]
Oh, good question!

For general event handling, you can subclass the viewer (just make sure to call `super` on the viewer's methods that you're overriding).

For example, here's a bit of code that prints "MOUSE PRESSED!" whenever you click the mouse:

```python
from pyrender import Mesh, Scene, Viewer
import trimesh

tm = trimesh.load_mesh('./models/fuze.obj')
mesh = Mesh.from_trimesh(tm)
scene = Scene()
scene.add(mesh)

class MyViewer(Viewer):

    def on_mouse_press(self, x, y, buttons, modifiers):
        print('MOUSE PRESSED!')
        super(MyViewer, self).on_mouse_press(x, y, buttons, modifiers)

v = MyViewer(scene, use_raymond_lighting=True)
```
Alternatively, if you're specifically interested in handling key presses, you can register callback functions using the `registered_keys` argument of the viewer's constructor [here](https://pyrender.readthedocs.io/en/latest/generated/pyrender.Viewer.html#pyrender.Viewer).

**Comment by mmatl** [comment]
Also, FYI, you can override any of the pyglet window function's event handlers, since the viewer is itself just a subclass of the Pyglet window function.

**Comment by mrlooi** [comment]
Yea figured, thanks for the project Matthew, great stuff!
