### ISSUE TITLE
size of the object in rendered depth image is small as compared to input mesh

### ISSUE THREAD

**Issue by mvish7** [mmatl/pyrender#58]
Hello, 

I'm trying to render the depth image from my point cloud. Below is the outline of code snippet i have tried.
```
fuze_trimesh = trimesh.load('.../teddyUpright2.ply')

#camera pose
transform_mat = np.linalg.inv((np.loadtxt(".../frame-000000.pose.txt", delimiter=' ')))

cam_intrinsics = np.loadtxt(.../camera-intrinsics.txt", delimiter=' ')

fuze_trimesh.apply_transform(transform_mat)

mesh = pyrender.Mesh.from_trimesh(fuze_trimesh)

scene = pyrender.Scene()

scene.add(mesh, pose=np.eye(4))

camera = pyrender.IntrinsicsCamera(cam_intrinsics[0, 0], cam_intrinsics[1, 1], cam_intrinsics[0, 2], cam_intrinsics[1, 2], 0.0001, 10000) 

camera_pose = np.eye(4)
camera_pose[2, 3] = 0.6

scene.add(camera, pose=camera_pose)

pyrender.Viewer(scene)

r = pyrender.OffscreenRenderer(640, 480)

color, depth = r.render(scene)

```

Now the actual issue:

The size of the object in the rendered depth image is very small as compared to the size of the object in image and even in imported mesh.

When i check the scale of the fuze_trimesh it is around 0.3045. i'm not able to figure out why the rendered depth image has small size?

any suggestions on why this is happening and how to solve this?

**Comment by mvish7** [comment]
I solved this problem by providing the pose of my camera while adding the mesh and the intrinsic camera in the scene. so this doesn't classify as an issue

**Comment by JQJ001** [comment]
Hello, I have the same problem as you: 'The size of the object in the rendered depth image is very small as compared to the size of the object in image and even in imported mesh.'

The pose and the intrinsic of my camera are generated by an image-based geometry reconstruction method [MVE](https://github.com/simonfuhrmann/mve). 
The original image:
![image](https://github.com/mmatl/pyrender/assets/31473581/4eda2863-f32b-495c-a175-25f58c707e36)
The .obj generated by [mvs-texturing](https://github.com/nmoehrle/mvs-texturing): 
![I{@T(M{{Z6)L9NT2AEL3_F3](https://github.com/mmatl/pyrender/assets/31473581/73f35f64-5d15-40ab-828a-23a3d1b0d4d6)
The rendered color image and depth image:
![image](https://github.com/mmatl/pyrender/assets/31473581/2ff39d38-26d6-487f-9bc4-0419ec1ead73)
![image](https://github.com/mmatl/pyrender/assets/31473581/3d73b287-dd95-4a23-8cb4-544291a0ba47)

any suggestions on why this is happening and how to solve this?
Thanks. Looking forward to your reply.
