### ISSUE TITLE
Citation for Pyrender

### ISSUE THREAD

**Issue by mvish7** [mmatl/pyrender#69]
Hello,
I'm making use of pyrender for research work. I would like to cite the pyrender library in my report.
Is there any citation available which I can use?

**Comment by mmatl** [comment]
Hi @mvish7 -- if you'd like to cite it, just provide a link to the Github repo! Thanks for using Pyrender!

**Comment by EdwardSmith1884** [comment]
This is what I used:

@misc{pyrender,
  author = {Matthew Matl},
  title = {Pyrender},
  year = {2019},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/mmatl/pyrender}}
}
