### ISSUE TITLE
Colab Example notebooks do not render correctly

### ISSUE THREAD

**Issue by joefriel** [mmatl/pyrender#85]
All three Colab example notebooks render incorrectly

![image](https://user-images.githubusercontent.com/3987049/70142520-66c74780-1667-11ea-97ea-3dbfcc5e98ac.png)

**Comment by ParikaGoel** [comment]
I am also facing the same problem....it is happening in my system as well....does anyone has any solution for this ?

**Comment by Guptajakala** [comment]
+1 for this issue

**Comment by gustavla** [comment]
+1 I'm also really eager to resolve this issue. I saw it on the Colab as well as on Ubuntu 18.04.

**Comment by gustavla** [comment]
I found a workaround by downgrading to pyrender==0.1.32.

@ParikaGoel @Guptajakala @joefriel

**Comment by Guptajakala** [comment]
@gustavla Thank you very much! Will give it a try.

**Comment by ParikaGoel** [comment]
> I found a workaround by downgrading to pyrender==0.1.32.
> 
> @ParikaGoel @Guptajakala @joefriel

@gustavla  Thank you very much. Rendering colors on 0.1.32 version works for me
