### ISSUE TITLE
Dose pyrender support raytrace rendering ?

### ISSUE THREAD

**Issue by v-wewei** [mmatl/pyrender#89]
Hi, @mmatl 
Seems the effect of pyrender do not satisfy me when i want to synthesize some of the real world scene. But the speed is really faster than most of the rendering Engine.
After some time diving into, maybe the most difference i can found was the rendering tech between blender and pyrender. blender support the raytrace rendering with headless remote server, and i can make sure the sythesize image look like more realistic . So, does pyrender will support the raytrace rendering tech in the near future? or if there is any non-official implementation of raytrace rendering can be used as plug in ? 
Thanks, very much !

**Comment by mmatl** [comment]
Hi, and thanks for the issue! Pyrender is not designed for raytracing, and I plan to only support raster rendering for the time being. I'd strongly recommend Blender (it's what I use for raytrace rendering), which you can script using Python directly!
