### ISSUE TITLE
can't see the color of glb model

### ISSUE THREAD

**Issue by Wisgon** [mmatl/pyrender#96]
Hi, I use pyrender to load my glb model, however, I can't see anything in the window, but when I press "N" button, I can see my model. So my model has no color...
I use the 3d editor tools for win10 to open my glb model, it has color and looks good!
So, it's not the problem of model, I wonder that what can I do to load the model correctly.

here is my code:
```
from pyrender import Mesh, Scene, Viewer
from io import BytesIO
import numpy as np
import trimesh


class MyViewer(Viewer):
	def __init__(self, scene):
		super(MyViewer, self).__init__(scene)


file = "../models/my_model.glb"
with open(file, "rb") as fp:

	duck = trimesh.load(BytesIO(fp.read()), file_type='glb')

	duckmesh = Mesh.from_trimesh(list(duck.geometry.values())[0])
	scene = Scene(ambient_light=np.array([1.0, 1.0, 1.0, 1.0]))
	scene.add(duckmesh)
	MyViewer(scene)
```

by the way, I get my_model.glb file from an obj file, converted by [obj2gltf](https://github.com/AnalyticalGraphicsInc/obj2gltf), using command `obj2gltf -i model.obj -o my_model.glb`, I try another obj model convert to glb file, all of them can't see color, no matter the obj file has jpg file to attach or not.

**Comment by mmatl** [comment]
@Wisgon I ran your code on Ubuntu 16.04 and I'm not experiencing this issue. Can you clone the repo and navigate to the examples folder, and then run duck.py? Or just run this code:
```
from pyrender import Mesh, Scene, Viewer
from io import BytesIO
import numpy as np
import trimesh
import requests

duck_source = "https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/Duck/glTF-Binary/Duck.glb"

duck = trimesh.load(BytesIO(requests.get(duck_source).content), file_type='glb')
duckmesh = Mesh.from_trimesh(list(duck.geometry.values())[0])
scene = Scene(ambient_light=np.array([1.0, 1.0, 1.0, 1.0]))
scene.add(duckmesh)
Viewer(scene)
```

**Comment by Wisgon** [comment]
I run the duck demo，it has color and works fine, maybe it's the problem of my own model.
