### ISSUE TITLE
offscreen rendering lacking colors 

### ISSUE THREAD

**Issue by nicolasugrinovic** [mmatl/pyrender#97]
Hi, thank you for your code. I am trying [this example from colab](https://colab.research.google.com/drive/1rTLHk0qxh4dn8KNe-mCnN8HAWdd2_BEh) and I get almost the same result, but the rendering fails to render all colors of the fuze object. The result is like this: 
![Selection_542](https://user-images.githubusercontent.com/25443240/71996356-5a24a900-323c-11ea-9112-2cc429d76ce6.png)
While I get a correct rendering using Trimesh `fuze_trimesh.show()` :
![Selection_543](https://user-images.githubusercontent.com/25443240/71996411-76284a80-323c-11ea-9ade-3ad6d07e5276.png)

**Comment by ParikaGoel** [comment]
Color rendering works on 0.1.32 version. Refer to issue #85
